In [1036]:
import pandas as pd
import  numpy as np
import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt

In [1037]:
df = pd.read_excel('../data/raw/dataset_v2.xlsx')
cols = df.columns

In [1038]:
df = pd.read_spss('../data/raw/followup.sav')
df = df[cols]

In [1039]:
print(df.shape)
df.head()

(3757, 36)


CODE  birthday   age  age.diag  age.menarc  age.menop    education  \
0  918.0    1352.0  42.0      42.0        13.0        NaN      primary   
1    NaN    1351.0   NaN      41.0        12.0        NaN  high school   
2    NaN    1324.0   NaN      67.0        14.0       45.0    illitrate   
3    NaN    1323.0  53.0      53.0        12.0        NaN   university   
4    3.0    1337.0   NaN      53.0        16.0       50.0      primary   

   marital   gravity  lactaton  ...                   Family agef  \
0  married    gravid      72.0  ...                       no    0   
1  married    gravid      27.0  ...   paternal second degree   38   
2    widow    gravid      84.0  ...  first degree (1 person)   36   
3  married  no child       0.0  ...    paternal third degree        
4  married    gravid      52.0  ...                       no        

        other.CA weight height                  cc RB.sign  LB.sign  sign  \
0             no   85.0  151.0  mass or thickening  normal     mass   NaN   
1  others cancer   69.0  158.0  mass or thickening     NaN      NaN  mass   
2   utrus cancer   63.0  145.0  mass or thickening     NaN      NaN   NaN   
3             no   55.0  157.0            followup     NaN      NaN  47.0   
4  others cancer   70.0  155.0        chemotherapy     NaN      NaN   NaN   

   location  
0       uoq  
1       uoq  
2       NaN  
3       uoq  
4       NaN  

[5 rows x 36 columns]

In [1040]:
df = df.drop('CODE', axis=1)
df = df.reset_index(drop=True)
df.head()

birthday   age  age.diag  age.menarc  age.menop    education  marital  \
0    1352.0  42.0      42.0        13.0        NaN      primary  married   
1    1351.0   NaN      41.0        12.0        NaN  high school  married   
2    1324.0   NaN      67.0        14.0       45.0    illitrate    widow   
3    1323.0  53.0      53.0        12.0        NaN   university  married   
4    1337.0   NaN      53.0        16.0       50.0      primary  married   

    gravity  lactaton  fpregnancy  ...                   Family agef  \
0    gravid      72.0        16.0  ...                       no    0   
1    gravid      27.0        20.0  ...   paternal second degree   38   
2    gravid      84.0        17.0  ...  first degree (1 person)   36   
3  no child       0.0         NaN  ...    paternal third degree        
4    gravid      52.0        19.0  ...                       no        

        other.CA weight height                  cc  RB.sign LB.sign  sign  \
0             no   85.0  151.0  mass or thickening   normal    mass   NaN   
1  others cancer   69.0  158.0  mass or thickening      NaN     NaN  mass   
2   utrus cancer   63.0  145.0  mass or thickening      NaN     NaN   NaN   
3             no   55.0  157.0            followup      NaN     NaN  47.0   
4  others cancer   70.0  155.0        chemotherapy      NaN     NaN   NaN   

   location  
0       uoq  
1       uoq  
2       NaN  
3       uoq  
4       NaN  

[5 rows x 35 columns]

In [1041]:
df.describe()

birthday          age     age.diag   age.menarc    age.menop  \
count   3701.000000  2802.000000  3725.000000  3544.000000  1400.000000   
mean    1267.820589    47.846181    47.569933    13.275113    47.352857   
std      368.487000    11.603018    11.585472     2.210664     6.144885   
min        0.000000     0.000000     0.000000     0.000000     1.000000   
25%     1331.000000    40.000000    39.000000    12.000000    45.000000   
50%     1340.000000    47.000000    47.000000    13.000000    48.000000   
75%     1349.000000    55.000000    54.000000    14.000000    51.000000   
max    13337.000000    87.000000    92.000000    46.000000    65.000000   

          lactaton   fpregnancy          hrt        datehys  agehysterectomy  \
count  3327.000000  3308.000000  3403.000000     281.000000      1175.000000   
mean     47.823865    20.502721     1.307670   93351.348754         5.643404   
std      42.837373     7.702060     9.901646  133928.501703        15.184767   
min       0.000000     0.000000     0.000000       0.000000         0.000000   
25%      18.000000    17.000000     0.000000       0.000000         0.000000   
50%      38.000000    20.000000     0.000000       0.000000         0.000000   
75%      72.000000    24.000000     0.000000  262920.000000         0.000000   
max     292.000000   156.000000   300.000000  320820.000000        82.000000   

         no.biopsy        weight       height  
count  3210.000000   3457.000000  3404.000000  
mean      0.491277     94.581429   158.653643  
std       0.548165   1430.178794    44.276715  
min       0.000000      0.000000     0.000000  
25%       0.000000     62.000000   154.000000  
50%       0.000000     70.000000   158.000000  
75%       1.000000     78.000000   162.000000  
max       3.000000  84156.000000  1601.000000

In [1042]:
df.dtypes

birthday            float64
age                 float64
age.diag            float64
age.menarc          float64
age.menop           float64
education          category
marital            category
gravity            category
lactaton            float64
fpregnancy          float64
infertility        category
kindinfertile      category
reproduct          category
mens               category
ocpuse             category
ocp                category
hrt                 float64
hystrectomy        category
datehys             float64
agehysterectomy     float64
smoking            category
no.biopsy           float64
personal.Hx        category
personal.other     category
date.other           object
Family             category
agef                 object
other.CA           category
weight              float64
height              float64
cc                 category
RB.sign            category
LB.sign            category
sign               category
location           category
dtype: object

In [1043]:
df.shape

(3757, 35)

In [1044]:
df.columns

Index(['birthday', 'age', 'age.diag', 'age.menarc', 'age.menop', 'education',
       'marital', 'gravity', 'lactaton', 'fpregnancy', 'infertility',
       'kindinfertile', 'reproduct', 'mens', 'ocpuse', 'ocp', 'hrt',
       'hystrectomy', 'datehys', 'agehysterectomy', 'smoking', 'no.biopsy',
       'personal.Hx', 'personal.other', 'date.other', 'Family', 'agef',
       'other.CA', 'weight', 'height', 'cc', 'RB.sign', 'LB.sign', 'sign',
       'location'],
      dtype='object')

In [1045]:
# columns_of_interest = ["event", "event2", "metastas2", "metastase1", "G"]
# # drop rows with missing values in the columns of interest (all)
# df = df.dropna(subset=columns_of_interest, how='all')
# df.shape

In [1046]:
# # get nan proportion for columns of interest
# df[columns_of_interest].isna().sum() / df.shape[0]

In [1047]:
# # use metastase1 as y and drop rows with missing values
# df = df.dropna(subset=['metastase1'], how='any')
# df.shape

In [1048]:
# get nan proportions for each column
df.isna().sum() / df.shape[0]

birthday           0.014906
age                0.254192
age.diag           0.008517
age.menarc         0.056694
age.menop          0.627362
education          0.055097
marital            0.028214
gravity            0.076391
lactaton           0.114453
fpregnancy         0.119510
infertility        0.153048
kindinfertile      0.693106
reproduct          0.056428
mens               0.186319
ocpuse             0.054565
ocp                0.412297
hrt                0.094224
hystrectomy        0.252063
datehys            0.925206
agehysterectomy    0.687250
smoking            0.062284
no.biopsy          0.145595
personal.Hx        0.054831
personal.other     0.062018
date.other         0.998669
Family             0.059622
agef               0.000000
other.CA           0.062816
weight             0.079851
height             0.093958
cc                 0.188714
RB.sign            0.796114
LB.sign            0.807825
sign               0.629225
location           0.479638
dtype: float64

In [1049]:
# # count cols with more than 30% missing values
# columns_to_drop = df.isnull().sum()[df.isnull().sum() > 0.3 * df.shape[0]].index
# len(columns_to_drop)

In [1050]:
# columns_to_drop

In [1051]:
# df = df.drop(columns_to_drop, axis=1)
# df.shape

In [1052]:
df.columns

Index(['birthday', 'age', 'age.diag', 'age.menarc', 'age.menop', 'education',
       'marital', 'gravity', 'lactaton', 'fpregnancy', 'infertility',
       'kindinfertile', 'reproduct', 'mens', 'ocpuse', 'ocp', 'hrt',
       'hystrectomy', 'datehys', 'agehysterectomy', 'smoking', 'no.biopsy',
       'personal.Hx', 'personal.other', 'date.other', 'Family', 'agef',
       'other.CA', 'weight', 'height', 'cc', 'RB.sign', 'LB.sign', 'sign',
       'location'],
      dtype='object')

In [1053]:
# sort cols by alphabets
df = df.reindex(sorted(df.columns), axis=1)
df.columns

Index(['Family', 'LB.sign', 'RB.sign', 'age', 'age.diag', 'age.menarc',
       'age.menop', 'agef', 'agehysterectomy', 'birthday', 'cc', 'date.other',
       'datehys', 'education', 'fpregnancy', 'gravity', 'height', 'hrt',
       'hystrectomy', 'infertility', 'kindinfertile', 'lactaton', 'location',
       'marital', 'mens', 'no.biopsy', 'ocp', 'ocpuse', 'other.CA',
       'personal.Hx', 'personal.other', 'reproduct', 'sign', 'smoking',
       'weight'],
      dtype='object')

In [1054]:
# get nan proportions for each column
df.isna().sum() / df.shape[0]

Family             0.059622
LB.sign            0.807825
RB.sign            0.796114
age                0.254192
age.diag           0.008517
age.menarc         0.056694
age.menop          0.627362
agef               0.000000
agehysterectomy    0.687250
birthday           0.014906
cc                 0.188714
date.other         0.998669
datehys            0.925206
education          0.055097
fpregnancy         0.119510
gravity            0.076391
height             0.093958
hrt                0.094224
hystrectomy        0.252063
infertility        0.153048
kindinfertile      0.693106
lactaton           0.114453
location           0.479638
marital            0.028214
mens               0.186319
no.biopsy          0.145595
ocp                0.412297
ocpuse             0.054565
other.CA           0.062816
personal.Hx        0.054831
personal.other     0.062018
reproduct          0.056428
sign               0.629225
smoking            0.062284
weight             0.079851
dtype: float64

## Preprocess columns

### Family

In [1055]:
col_name = 'Family'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in Family column:  224
Proportion of nan values in Family column:  0.05962203886079319
category


In [1056]:
df[col_name].unique()

['no', 'paternal second degree', 'first degree (1 person)', 'paternal third degree', 23.0, ..., 45.0, 55.0, 41.0, 51.0, 44.0]
Length: 26
Categories (25, object): [13.0, 14.0, 15.0, 17.0, ..., 'maternal third degree', 'no', 'paternal second degree', 'paternal third degree']

In [1057]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1058]:
df[col_name] = df[col_name].astype(str)
df[col_name] = df[col_name].replace('nan', 0)
df[col_name] = df[col_name].replace('no', 0)
vals = df[col_name].unique().tolist()
vals.remove(0)
df[col_name] = df[col_name].replace(vals, 1)
print(df[col_name].value_counts())

0    3139
1     618
Name: Family, dtype: int64


In [1059]:
fig = px.pie(df[col_name].value_counts(), values=df[col_name].value_counts().values, names=df[col_name].value_counts().index, title=col_name)
fig.show()

### LB.sign

In [1060]:
col_name = 'LB.sign'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in LB.sign column:  3035
Proportion of nan values in LB.sign column:  0.8078253926004791
category


In [1061]:
df[col_name].unique()

['mass', NaN, 'thickening', 'nodularity', 'normal', ..., 'peod orange', 931.0, 401.0, 1031.0, 11.0]
Length: 57
Categories (56, object): [11.0, 13.0, 19.0, 21.0, ..., 'paget sign', 'peod orange', 'thickening', 'ulcer']

In [1062]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1063]:
# fill
df[col_name] = df[col_name].astype(str)
df[col_name] = df[col_name].replace('nan', 0)
vals = df[col_name].unique().tolist()
vals.remove(0)
df[col_name] = df[col_name].replace(vals, 1)
print(df[col_name].value_counts())

0    3035
1     722
Name: LB.sign, dtype: int64


In [1064]:
fig = px.pie(df[col_name].value_counts(), values=df[col_name].value_counts().values, names=df[col_name].value_counts().index, title=col_name)
fig.show()

### RB.sign

In [1065]:
col_name = 'RB.sign'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in RB.sign column:  2991
Proportion of nan values in RB.sign column:  0.7961139206813947
category


In [1066]:
df[col_name].unique()

['normal', NaN, 532.0, 12.0, 'nodularity', ..., 29.0, 109.0, 431.0, 'ecimose', 11.0]
Length: 47
Categories (46, object): [11.0, 12.0, 14.0, 19.0, ..., 'normal', 'paget sign', 'thickening', 'ulcer']

In [1067]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1068]:
# fill
df[col_name] = df[col_name].astype(str)
df[col_name] = df[col_name].replace('nan', 0)
vals = df[col_name].unique().tolist()
vals.remove(0)
df[col_name] = df[col_name].replace(vals, 1)
print(df[col_name].value_counts())

0    2991
1     766
Name: RB.sign, dtype: int64


In [1069]:
fig = px.pie(df[col_name].value_counts(), values=df[col_name].value_counts().values, names=df[col_name].value_counts().index, title=col_name)
fig.show()

### birthday

In [1070]:
col_name = 'birthday'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in birthday column:  56
Proportion of nan values in birthday column:  0.014905509715198297
float64


In [1071]:
df[col_name].unique()

array([ 1352.,  1351.,  1324.,  1323.,  1337.,  1331.,  1333.,  1327.,
        1317.,  1321.,  1334.,  1326.,  1346.,  1344.,  1336.,  1316.,
        1339.,  1329.,  1325.,  1343.,  1349.,  1330.,  1345.,  1319.,
        1313.,  1305.,  1332.,  1322.,  1340.,  1311.,  1314.,    nan,
        1320.,  1348.,  1315.,  1335.,  1338.,  1308.,  1309.,  1347.,
        1328.,  1341.,  1350.,  1342.,  1318.,  1310.,  1306.,  1354.,
        1356.,  1304.,  1353.,  1302.,  1355.,  1303.,  1312.,  1359.,
        1307.,  1300.,  1357.,  1367.,  1362.,  1358.,  1360.,  1361.,
        1365.,  1363.,  1368.,  1364.,  1369.,  1366.,  1370.,    19.,
        1968.,    35.,     0.,  1371., 13337.,    39.])

In [1072]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1073]:
# fill
df[col_name] = df[col_name].replace(13337, 1337)
df[col_name] = df[col_name].replace(35, 1335)
df[col_name] = df[col_name].replace(0, np.nan)

In [1074]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

### Age

In [1075]:
col_name = 'age'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in age column:  955
Proportion of nan values in age column:  0.2541921746073995
float64


In [1076]:
df[col_name].unique()

array([42., nan, 53., 63., 41., 43., 49., 59., 55., 50., 30., 32., 40.,
       60., 39., 47., 51., 45., 33., 27., 46., 31., 57., 71., 44., 25.,
       54., 52., 37., 65., 29., 58., 62., 79., 48., 69., 64., 68., 38.,
       28., 56., 36., 66., 61., 35., 26., 34., 72., 23., 75., 70., 74.,
       78., 67., 73., 77., 87., 76., 83., 81., 18., 82., 80., 24., 84.,
       85.,  0.])

In [1077]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1078]:
# count rows with nan age but values in birthday
df[df['age'].isna() & df['birthday'].notna()].shape

(916, 35)

In [1079]:
this_year = 1402
# fill age with this_year - birthday if age is nan and birthday is not nan
df.loc[df['age'].isna() & df['birthday'].notna(), 'age'] = df.loc[df['age'].isna() & df['birthday'].notna(), 'birthday'].apply(lambda x: abs(this_year - x))
# check age > 100 and < 0 set to nan
df.loc[(df['age'] > 100) | (df['age'] < 0), 'age'] = np.nan
# drop birthday column
df = df.drop('birthday', axis=1)
print(df[col_name].isna().sum())

41


In [1080]:
df[col_name] = df[col_name].fillna(df[col_name].mean())

In [1081]:
# histogram
fig = px.histogram(df, x=col_name)
fig.show()

### age.diag

In [1082]:
col_name = 'age.diag'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in age.diag column:  32
Proportion of nan values in age.diag column:  0.008517434122970456
float64


In [1083]:
df[col_name].unique()

array([42., 41., 67., 53., 63., 35., 40., 46., 57., 43., 48., 30., 32.,
       60., 38., 37., 54., 51., 44., 29., 50., 27., 52., 55., 31., 71.,
       25., 39., 49., 45., 64., 33., nan, 28., 56., 62., 58., 79., 47.,
       61., 68., 36., 66., 26., 65., 34., 59., 72., 24., 75., 70., 73.,
       74., 78., 76., 69., 87., 77., 83., 82., 81., 18., 80., 22., 89.,
       21., 86., 84., 92., 85., 23., 16.,  0.])

In [1084]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1085]:
# count rows missing age.diag
print(df[df['age.diag'].isna()].shape)
# count rows missing age.diag but available age (count)
print(df[(df['age.diag'].isna()) & (df['age'].notna())].shape)

(32, 34)
(32, 34)


In [1086]:
# fill age.diag with age
df['age.diag'] = df['age.diag'].fillna(df['age'])

In [1087]:
# plot histogram of age.diag
fig = px.histogram(df, x='age.diag', nbins=20, title='Histogram of age.diag')
fig.show()

### age.menarc

In [1088]:
col_name = 'age.menarc'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in age.menarc column:  213
Proportion of nan values in age.menarc column:  0.05669417088102209
float64


In [1089]:
df[col_name].unique()
# df[col_name].value_counts()

array([13., 12., 14., 16., 15., 11., 18.,  9., nan, 20., 10., 17.,  8.,
       24., 29.,  0.,  1., 46.])

In [1090]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1091]:
df[col_name] = df[col_name].fillna(13)
for i in range(df.shape[0]):
    if df[col_name][i] > 20:
        df[col_name][i] = 13

/tmp/ipykernel_6862/2616763665.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [1092]:
# plot histogram
fig = px.histogram(df, x=col_name, nbins=20, title=f'Histogram of {col_name}')
fig.show()

### age.menop

In [1093]:
col_name = 'age.menop'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in age.menop column:  2357
Proportion of nan values in age.menop column:  0.6273622571200426
float64


In [1094]:
# df[col_name].value_counts()
df[col_name].unique()

array([nan, 45., 50., 39., 48., 43., 42., 34., 40., 52., 46., 53., 56.,
       44., 60., 47., 30., 57., 49., 51., 54., 41., 33., 55., 32., 36.,
       59., 38., 35., 37., 62., 58., 64., 29., 61., 31., 65., 14., 28.,
        1.,  3.,  4.,  2., 13.])

In [1095]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1096]:
# drop age.menop column
df = df.drop('age.menop', axis=1)

### agef

In [1097]:
col_name = 'agef'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in agef column:  0
Proportion of nan values in agef column:  0.0
object


In [1098]:
df[col_name].value_counts()

      2426
0      852
50      53
40      47
45      33
      ... 
66       1
51       1
58       1
31       1
83       1
Name: agef, Length: 62, dtype: int64

In [1099]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1100]:
# delete agef column
df = df.drop('agef', axis=1)

### agehysterectomy

In [1101]:
col_name = 'agehysterectomy'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in agehysterectomy column:  2582
Proportion of nan values in agehysterectomy column:  0.6872504657971786
float64


In [1102]:
# df[col_name].value_counts()
df[col_name].unique()

array([ 0., nan, 43., 47., 51., 46., 40., 42., 55., 49., 38., 48., 52.,
       45., 57., 50., 30., 44., 36., 58., 37., 34., 33., 39., 41., 61.,
       31., 54., 82., 56., 59., 32., 35., 53., 62.,  1.])

In [1103]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1104]:
df = df.drop('agehysterectomy', axis=1)

### cc

In [1105]:
col_name = 'cc'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in cc column:  709
Proportion of nan values in cc column:  0.18871439978706414
category


In [1106]:
# df[col_name].value_counts()
df[col_name].unique()

['mass or thickening', 'followup', 'chemotherapy', 'skin symptom', 'mass & discharge', ..., 32.0, 42.0, 11.0, 150.0, 33.0]
Length: 35
Categories (34, object): [11.0, 13.0, 15.0, 16.0, ..., 'others', 'pain', 'screening', 'skin symptom']

In [1107]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1108]:
df = df.drop('cc', axis=1)

### date.other

In [1109]:
col_name = 'date.other'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in date.other column:  3752
Proportion of nan values in date.other column:  0.9986691509182859
object


In [1110]:
# df[col_name].value_counts()
df[col_name].unique()

array([nan, datetime.date(1991, 12, 13), datetime.date(1989, 6, 6),
       datetime.date(1973, 1, 1), datetime.date(1969, 1, 1),
       datetime.date(1994, 1, 1)], dtype=object)

In [1111]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1112]:
df = df.drop('date.other', axis=1)

### datehys

In [1113]:
col_name = 'datehys'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in datehys column:  3476
Proportion of nan values in datehys column:  0.9252062816076657
float64


In [1114]:
# df[col_name].value_counts()
df[col_name].unique()

array([       nan, 3.1026e+05, 2.8476e+05, 3.1344e+05, 3.1332e+05,
       2.6310e+05, 3.0996e+05, 2.6676e+05, 3.1032e+05, 2.8116e+05,
       2.9892e+05, 3.1704e+05, 2.9910e+05, 2.8110e+05, 2.7036e+05,
       3.0618e+05, 2.4516e+05, 2.9556e+05, 2.4150e+05, 2.5266e+05,
       2.5212e+05, 2.7408e+05, 2.7792e+05, 2.8446e+05, 2.3076e+05,
       2.9952e+05, 2.1996e+05, 2.7390e+05, 3.0252e+05, 2.9232e+05,
       2.8830e+05, 3.1386e+05, 2.4492e+05, 2.5974e+05, 2.3814e+05,
       3.1392e+05, 2.8134e+05, 2.5926e+05, 2.5236e+05, 2.5950e+05,
       3.1368e+05, 2.9550e+05, 3.1746e+05, 2.5944e+05, 1.8036e+05,
       2.6292e+05, 2.8842e+05, 2.9544e+05, 2.9226e+05, 3.1014e+05,
       2.9526e+05, 2.8470e+05, 2.2710e+05, 3.0276e+05, 2.8806e+05,
       3.0294e+05, 2.8152e+05, 2.7756e+05, 3.1692e+05, 2.8812e+05,
       2.8836e+05, 3.1356e+05, 3.2082e+05, 3.0636e+05, 2.4876e+05,
       2.3796e+05, 2.2356e+05, 2.9196e+05, 3.1716e+05, 2.5956e+05,
       3.2076e+05, 4.0000e+01, 5.5000e+01, 0.0000e+00, 5.0000e

In [1115]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1116]:
df = df.drop('datehys', axis=1)

### education

In [1117]:
col_name = 'education'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in education column:  207
Proportion of nan values in education column:  0.05509715198296513
category


In [1118]:
# df[col_name].value_counts()
df[col_name].unique()

['primary', 'high school', 'illitrate', 'university', NaN, ..., 44.0, 33.0, 22.0, 50.0, 52.0]
Length: 11
Categories (10, object): [0.0, 22.0, 33.0, 44.0, ..., 'high school', 'illitrate', 'primary', 'university']

In [1119]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1120]:
# fill nan with mode
df[col_name] = df[col_name].fillna(df[col_name].mode()[0])

In [1121]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

### fpregnancy

In [1122]:
col_name = 'fpregnancy'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in fpregnancy column:  449
Proportion of nan values in fpregnancy column:  0.1195102475379292
float64


In [1123]:
# df[col_name].value_counts()
df[col_name].unique()

array([ 16.,  20.,  17.,  nan,  19.,  23.,  15.,  24.,  21.,  22.,  18.,
        40.,  13.,  34.,  32.,  25.,  29.,  31.,  26.,  14.,  33.,  30.,
        35.,  27.,  28.,  36.,  45.,  41.,  37.,  42.,  38.,   0.,  43.,
        39., 156.])

In [1124]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1125]:
# fill nan with 0
df[col_name] = df[col_name].fillna(0)

In [1126]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

### gravity

In [1127]:
col_name = 'gravity'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in gravity column:  287
Proportion of nan values in gravity column:  0.07639073729039127
category


In [1128]:
# df[col_name].value_counts()
df[col_name].unique()

['gravid', 'no child', NaN, 'infertile', 3.0, 5.0, 4.0, 11.0]
Categories (7, object): [3.0, 4.0, 5.0, 11.0, 'gravid', 'infertile', 'no child']

In [1129]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1130]:
# fill
df[col_name] = df[col_name].astype(str)
df[col_name] = df[col_name].replace('nan', 0)
df[col_name] = df[col_name].replace('no child', 0)
vals = df[col_name].unique().tolist()
vals.remove(0)

df[col_name] = df[col_name].replace(vals, 1)
print(df[col_name].value_counts())

1    3251
0     506
Name: gravity, dtype: int64


In [1131]:
fig = px.pie(df[col_name].value_counts(), values=df[col_name].value_counts().values, names=df[col_name].value_counts().index, title=col_name)
fig.show()

### height

In [1132]:
col_name = 'height'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in height column:  353
Proportion of nan values in height column:  0.09395794516901783
float64


In [1133]:
# df[col_name].value_counts()
df[col_name].unique()

array([1.510e+02, 1.580e+02, 1.450e+02, 1.570e+02, 1.550e+02, 1.620e+02,
       1.650e+02, 1.540e+02, 1.530e+02, 1.470e+02, 1.600e+02, 1.520e+02,
       1.500e+02, 1.640e+02, 1.660e+02, 1.560e+02, 1.670e+02, 1.320e+02,
       1.680e+02, 1.610e+02, 1.590e+02, 1.630e+02,       nan, 1.440e+02,
       1.480e+02, 1.490e+02, 1.460e+02, 1.300e+02, 1.430e+02, 1.710e+02,
       1.780e+02, 1.240e+02, 1.420e+02, 1.730e+02, 1.720e+02, 1.740e+02,
       1.400e+02, 1.700e+02, 1.200e+02, 1.690e+02, 1.750e+02, 1.410e+02,
       1.380e+02, 1.370e+02, 1.360e+02, 1.760e+02, 1.390e+02, 1.850e+02,
       1.790e+02, 1.600e+03, 0.000e+00, 3.000e+00, 1.601e+03, 6.500e+01,
       1.010e+02, 1.000e+00])

In [1134]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1135]:
# fill < 100 with nan
df.loc[df[col_name] < 100, col_name] = np.nan

In [1136]:
# fill nan with mean
df[col_name] = df[col_name].fillna(df[col_name].mean())

In [1137]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

### hrt

In [1138]:
col_name = 'hrt'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in hrt column:  354
Proportion of nan values in hrt column:  0.09422411498536067
float64


In [1139]:
# df[col_name].value_counts()
df[col_name].unique()

array([  0.,  nan,   2.,   6.,  24.,  12.,  96.,   4.,  36.,   3.,  30.,
        18.,  72.,  48.,   5.,  60.,   9.,   8.,  54.,  42.,  10., 120.,
       102.,   1., 300., 145.,  78.,  90.,  66.,   7.])

In [1140]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1141]:
# fill
df[col_name] = df[col_name].astype(str)
df[col_name] = df[col_name].replace('nan', 0)
vals = df[col_name].unique().tolist()
vals.remove(0)
df[col_name] = df[col_name].replace(vals, 1)
print(df[col_name].value_counts())

1    3403
0     354
Name: hrt, dtype: int64


In [1142]:
fig = px.pie(df[col_name].value_counts(), values=df[col_name].value_counts().values, names=df[col_name].value_counts().index, title=col_name)
fig.show()

### hystrectomy

In [1143]:
col_name = 'hystrectomy'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in hystrectomy column:  947
Proportion of nan values in hystrectomy column:  0.2520628160766569
category


In [1144]:
# df[col_name].value_counts()
df[col_name].unique()

['no', NaN, 12.0, 'hystrectomy', 'uni lateral oophorectomy', 13.0, 49.0, 45.0, 43.0, 29.0]
Categories (9, object): [12.0, 13.0, 29.0, 43.0, ..., 49.0, 'hystrectomy', 'no', 'uni lateral oophorectomy']

In [1145]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1146]:
# fill
df[col_name] = df[col_name].astype(str)
df[col_name] = df[col_name].replace('nan', 0)
df[col_name] = df[col_name].replace('no', 0)
vals = df[col_name].unique().tolist()
vals.remove(0)
df[col_name] = df[col_name].replace(vals, 1)
print(df[col_name].value_counts())

0    3510
1     247
Name: hystrectomy, dtype: int64


In [1147]:
fig = px.pie(df[col_name].value_counts(), values=df[col_name].value_counts().values, names=df[col_name].value_counts().index, title=col_name)
fig.show()

### infertility

In [1148]:
col_name = 'infertility'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in infertility column:  575
Proportion of nan values in infertility column:  0.15304764439712537
category


In [1149]:
# df[col_name].value_counts()
df[col_name].unique()

['no', NaN, 'yes', 6.0]
Categories (3, object): [6.0, 'no', 'yes']

In [1150]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1151]:
# fill
df[col_name] = df[col_name].astype(str)
df[col_name] = df[col_name].replace('nan', 0)
df[col_name] = df[col_name].replace('no', 0)
vals = df[col_name].unique().tolist()
vals.remove(0)
df[col_name] = df[col_name].replace(vals, 1)
print(df[col_name].value_counts())

0    3638
1     119
Name: infertility, dtype: int64


In [1152]:
fig = px.pie(df[col_name].value_counts(), values=df[col_name].value_counts().values, names=df[col_name].value_counts().index, title=col_name)
fig.show()

### kindinfertile

In [1153]:
col_name = 'kindinfertile'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in kindinfertile column:  2604
Proportion of nan values in kindinfertile column:  0.6931062017567208
category


In [1154]:
# df[col_name].value_counts()
df[col_name].unique()

[0.0, NaN, 5.0, 'HMG ,HCG injection', 12.0, ..., 'unknown', 34.0, 14.0, 31.0, 21.0]
Length: 16
Categories (15, object): [0.0, 5.0, 9.0, 12.0, ..., 'HMG ,HCG injection', 'IVF,ZIFT,GIFT,IUI,microinjection', 'clomifen', 'unknown']

In [1155]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1156]:
df = df.drop('kindinfertile', axis=1)

### lactaton

In [1157]:
col_name = 'lactaton'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in lactaton column:  430
Proportion of nan values in lactaton column:  0.11445302102741549
float64


In [1158]:
# df[col_name].value_counts()
df[col_name].unique()

array([ 72.,  27.,  84.,   0.,  52., 150.,  78.,  18., 168.,  36.,  60.,
        48.,  19., 216.,  24.,  10.,  15.,   9.,  30.,  96., 180.,   6.,
       144.,  56.,  nan,  11.,   3.,   4.,   8.,  25.,  12.,   1.,  42.,
        29.,  66., 192., 120.,  54.,   5.,  50., 132.,  92.,  28.,  80.,
        16.,  40.,  20., 174.,  13.,  90.,  64.,  65.,  17.,  53.,  89.,
       108.,  22.,  14.,   7.,  39., 100.,   2.,  55.,  75., 102.,  33.,
        21.,  44.,  51.,  58., 133.,  79.,  61.,  41., 114.,  43.,  32.,
       240., 118.,  38., 162.,  45.,  46., 171.,  86., 204.,  88., 138.,
        26., 126., 288., 113.,  62., 156.,  68.,  82.,  35.,  67.,  31.,
        57.,  77.,  37.,  69.,  47.,  23., 104.,  49., 101., 264.,  34.,
        81.,  99.,  76., 131., 163., 252.,  93.,  63., 130., 110.,  74.,
       160., 170., 200., 124., 166., 292., 206.])

In [1159]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1160]:
# fill nan with 0
df[col_name] = df[col_name].fillna(0)

In [1161]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

### location

In [1162]:
col_name = 'location'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in location column:  1802
Proportion of nan values in location column:  0.4796380090497738
category


In [1163]:
# df[col_name].value_counts()
df[col_name].unique()

['uoq', NaN, 'liq', 'uiq', 'three quadrant', ..., 0.0, 51.0, 111100.0, 11.0, 55.0]
Length: 56
Categories (55, object): [0.0, 11.0, 15.0, 16.0, ..., 'uiq', 'uoq', 'uoq and liq', 'upper half']

In [1164]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1165]:
df = df.drop('location', axis=1)

### marital

In [1166]:
col_name = 'marital'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in marital column:  106
Proportion of nan values in marital column:  0.028214000532339634
category


In [1167]:
# df[col_name].unique()
df[col_name].value_counts()

married    2940
widow       410
single      255
0.0          23
divorce      15
22.0          8
Name: marital, dtype: int64

In [1168]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1169]:
# fill
df[col_name] = df[col_name].fillna(0)
df[col_name] = df[col_name].astype(str)
df[col_name] = df[col_name].replace('22.0', 'married')
df[col_name] = df[col_name].replace('0.0', 'single')

In [1170]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

### mens

In [1171]:
col_name = 'mens'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in mens column:  700
Proportion of nan values in mens column:  0.18631887143997872
category


In [1172]:
# df[col_name].value_counts()
df[col_name].unique()

['regular', 'no', NaN, 'Irregular', 3.0, 22.0, 11.0, 49.0]
Categories (7, object): [3.0, 11.0, 22.0, 49.0, 'Irregular', 'no', 'regular']

In [1173]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1174]:
# fill
df[col_name] = df[col_name].astype(str)
df[col_name] = df[col_name].replace('3.0', 'nan')
df[col_name] = df[col_name].replace('11.0', 'nan')
df[col_name] = df[col_name].replace('22.0', 'nan')
df[col_name] = df[col_name].replace('49.0', 'nan')
df[col_name] = df[col_name].replace('nan', 'no')

In [1175]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

### no.biopsy

In [1176]:
col_name = 'no.biopsy'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in no.biopsy column:  547
Proportion of nan values in no.biopsy column:  0.1455948895395262
float64


In [1177]:
df[col_name].value_counts()
# df[col_name].unique()

0.0    1704
1.0    1445
2.0      51
3.0      10
Name: no.biopsy, dtype: int64

In [1178]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1179]:
# fill
df[col_name] = df[col_name].fillna(0)

In [1180]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

### ocp

In [1181]:
col_name = 'ocp'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in ocp column:  1549
Proportion of nan values in ocp column:  0.4122970455150386
category


In [1182]:
# df[col_name].value_counts()
df[col_name].unique()

[36.0, NaN, 150.0, 84.0, 216.0, ..., 270.0, 146.0, 11.0, 134.0, 166.0]
Length: 103
Categories (102, object): [2.0, 3.0, 4.0, 5.0, ..., 348.0, 360.0, 'duration(m)', 'no']

In [1183]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1184]:
# fill
df[col_name] = df[col_name].astype(str)
df[col_name] = df[col_name].replace('nan', 0.0)
df[col_name] = df[col_name].replace('no', 0.0)
df[col_name] = df[col_name].replace('duration(m)', 0.0)

In [1185]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

### ocpuse

In [1186]:
col_name = 'ocpuse'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in ocpuse column:  205
Proportion of nan values in ocpuse column:  0.054564812350279476
category


In [1187]:
df[col_name].unique()
# df[col_name].value_counts()

['yes', 'no', NaN, 60.0, 3.0, 11.0, 4.0, 240.0, 2.0]
Categories (8, object): [2.0, 3.0, 4.0, 11.0, 60.0, 240.0, 'no', 'yes']

In [1188]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1189]:
# fill
df[col_name] = df[col_name].astype(str)
df[col_name] = df[col_name].replace('nan', 0)
df[col_name] = df[col_name].replace('no', 0)
vals = df[col_name].unique().tolist()
vals.remove(0)
df[col_name] = df[col_name].replace(vals, 1)
print(df[col_name].value_counts())

0    2079
1    1678
Name: ocpuse, dtype: int64


In [1190]:
fig = px.pie(df[col_name].value_counts(), values=df[col_name].value_counts().values, names=df[col_name].value_counts().index, title=col_name)
fig.show()

### other.CA

In [1191]:
col_name = 'other.CA'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in other.CA column:  236
Proportion of nan values in other.CA column:  0.06281607665690711
category


In [1192]:
# df[col_name].value_counts()
df[col_name].unique()

['no', 'others cancer', 'utrus cancer', 'colon cancer', 'prostate cancer', ..., 266.0, 35666.0, 24.0, 53.0, 85.0]
Length: 35
Categories (34, object): [11.0, 15.0, 23.0, 24.0, ..., 'others cancer', 'ovarian cancer', 'prostate cancer', 'utrus cancer']

In [1193]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1194]:
# fill
df[col_name] = df[col_name].astype(str)
df[col_name] = df[col_name].replace('nan', 0)
df[col_name] = df[col_name].replace('no', 0)
vals = df[col_name].unique().tolist()
vals.remove(0)
df[col_name] = df[col_name].replace(vals, 1)
print(df[col_name].value_counts())

0    2919
1     838
Name: other.CA, dtype: int64


In [1195]:
fig = px.pie(df[col_name].value_counts(), values=df[col_name].value_counts().values, names=df[col_name].value_counts().index, title=col_name)
fig.show()

### personal.Hx

In [1196]:
col_name = 'personal.Hx'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in personal.Hx column:  206
Proportion of nan values in personal.Hx column:  0.05483098216662231
category


In [1197]:
df[col_name].value_counts()

no     2256
yes    1295
Name: personal.Hx, dtype: int64

In [1198]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1199]:
# fill
df[col_name] = df[col_name].astype(str)
df[col_name] = df[col_name].replace('nan', 'no')
df[col_name] = df[col_name].replace('no', 0)
vals = df[col_name].unique().tolist()
vals.remove(0)
df[col_name] = df[col_name].replace(vals, 1)
print(df[col_name].value_counts())

0    2462
1    1295
Name: personal.Hx, dtype: int64


In [1200]:
fig = px.pie(df[col_name].value_counts(), values=df[col_name].value_counts().values, names=df[col_name].value_counts().index, title=col_name)
fig.show()

### personal.other

In [1201]:
col_name = 'personal.other'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in personal.other column:  233
Proportion of nan values in personal.other column:  0.06201756720787863
category


In [1202]:
df[col_name].value_counts()

no             3498
ovary            18
others            3
13.0              1
colon             1
endometrium       1
lymphoma          1
meningioma        1
Name: personal.other, dtype: int64

In [1203]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1204]:
# fill
df[col_name] = df[col_name].astype(str)
df[col_name] = df[col_name].replace('nan', 'no')
df[col_name] = df[col_name].replace('no', 0)
vals = df[col_name].unique().tolist()
vals.remove(0)
df[col_name] = df[col_name].replace(vals, 1)
print(df[col_name].value_counts())

0    3731
1      26
Name: personal.other, dtype: int64


In [1205]:
fig = px.pie(df[col_name].value_counts(), values=df[col_name].value_counts().values, names=df[col_name].value_counts().index, title=col_name)
fig.show()

### reproduct

In [1206]:
col_name = 'reproduct'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in reproduct column:  212
Proportion of nan values in reproduct column:  0.05642800106467927
category


In [1207]:
df[col_name].value_counts()

premenopouse     1618
postmenopouse    1365
primenopouse      416
0.0               106
lactating          14
pregnant           14
11.0                7
33.0                5
Name: reproduct, dtype: int64

In [1208]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1209]:
# fill nan with 0
df[col_name] = df[col_name].fillna(0)

In [1210]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

### sign

In [1211]:
col_name = 'sign'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in sign column:  2364
Proportion of nan values in sign column:  0.6292254458344424
category


In [1212]:
# df[col_name].value_counts()
df[col_name].unique()

[NaN, 'mass', 47.0, 'normal', 27.0, ..., 12456.0, 158.0, 12467.0, 479.0, 5679.0]
Length: 112
Categories (111, object): [11.0, 12.0, 13.0, 14.0, ..., 'normal', 'others', 'peaud'orange', 'thickening']

In [1213]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1214]:
df = df.drop('sign', axis=1)

### smoking

In [1215]:
col_name = 'smoking'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in smoking column:  234
Proportion of nan values in smoking column:  0.06228373702422145
category


In [1216]:
df[col_name].value_counts()

no              2992
first degree     395
yes              127
12.0               8
48.0               1
Name: smoking, dtype: int64

In [1217]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1218]:
# fill
df[col_name] = df[col_name].astype(str)
df[col_name] = df[col_name].replace('nan', 'no')
df[col_name] = df[col_name].replace('no', 0)
vals = df[col_name].unique().tolist()
vals.remove(0)
df[col_name] = df[col_name].replace(vals, 1)
print(df[col_name].value_counts())

0    3226
1     531
Name: smoking, dtype: int64


In [1219]:
fig = px.pie(df[col_name].value_counts(), values=df[col_name].value_counts().values, names=df[col_name].value_counts().index, title=col_name)
fig.show()

### weight

In [1220]:
col_name = 'weight'
print(f'Number of nan values in {col_name} column: ', df[col_name].isna().sum())
print(f'Proportion of nan values in {col_name} column: ', df[col_name].isna().sum() / df.shape[0])
print(df[col_name].dtype)

Number of nan values in weight column:  300
Proportion of nan values in weight column:  0.07985094490284801
float64


In [1221]:
# df[col_name].value_counts()
df[col_name].unique()

array([8.5000e+01, 6.9000e+01, 6.3000e+01, 5.5000e+01, 7.0000e+01,
       8.9000e+01, 7.8000e+01, 8.6000e+01, 6.4000e+01, 7.1000e+01,
       4.3000e+01, 5.8000e+01, 5.0000e+01, 4.8000e+01, 6.1000e+01,
       5.3000e+01, 6.7000e+01, 6.8000e+01, 6.0000e+01, 3.5000e+01,
       7.5000e+01, 4.9000e+01, 5.9000e+01, 6.5000e+01, 7.6000e+01,
       5.7000e+01, 5.6000e+01, 7.4000e+01, 5.2000e+01,        nan,
       4.5000e+01, 5.4000e+01, 7.2000e+01, 5.1000e+01, 1.0000e+02,
       8.0000e+01, 9.0000e+01, 9.5000e+01, 6.2000e+01, 7.7000e+01,
       7.9000e+01, 4.6000e+01, 6.6000e+01, 7.3000e+01, 4.0000e+01,
       8.4000e+01, 8.1000e+01, 9.3000e+01, 8.8000e+01, 3.8000e+01,
       8.3000e+01, 3.6000e+01, 4.1000e+01, 1.0500e+02, 9.2000e+01,
       9.9000e+01, 4.4000e+01, 9.6000e+01, 8.2000e+01, 1.0400e+02,
       1.0300e+02, 9.4000e+01, 1.0100e+02, 1.0200e+02, 8.7000e+01,
       1.1400e+02, 1.1300e+02, 9.7000e+01, 9.8000e+01, 1.1100e+02,
       1.1200e+02, 1.0700e+02, 4.2000e+01, 9.1000e+01, 1.0800e

In [1222]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1223]:
# fill nan with mean
df[col_name] = df[col_name].replace(0, np.nan)
df[col_name] = df[col_name].fillna(df[col_name].mean())

In [1224]:
# plot bar chart of Family column (x values, y counts)
stats = df[col_name].value_counts().to_dict()
stats = {str(k): v for k, v in stats.items()}
stats['nan'] = df[col_name].isna().sum()
fig = px.bar(x=list(stats.keys()), y=list(stats.values()))
fig.show()

In [1227]:
df.head()

Family  LB.sign  RB.sign   age  age.diag  age.menarc    education  \
0       0        1        1  42.0      42.0        13.0      primary   
1       1        0        0  51.0      41.0        12.0  high school   
2       1        0        0  78.0      67.0        14.0    illitrate   
3       1        0        0  53.0      53.0        12.0   university   
4       0        0        0  65.0      53.0        16.0      primary   

   fpregnancy  gravity  height  ...     mens  no.biopsy   ocp  ocpuse  \
0        16.0        1   151.0  ...  regular        0.0  36.0       1   
1        20.0        1   158.0  ...  regular        1.0   0.0       0   
2        17.0        1   145.0  ...       no        1.0   0.0       0   
3         0.0        0   157.0  ...       no        0.0   0.0       1   
4        19.0        1   155.0  ...       no        1.0   0.0       0   

  other.CA personal.Hx  personal.other      reproduct  smoking  weight  
0        0           0               0   premenopouse        0    85.0  
1        1           1               0   premenopouse        0    69.0  
2        1           1               0  postmenopouse        1    63.0  
3        0           0               0   primenopouse        1    55.0  
4        1           1               0  postmenopouse        0    70.0  

[5 rows x 25 columns]

In [1226]:
print(df.isna().sum())

Family            0
LB.sign           0
RB.sign           0
age               0
age.diag          0
age.menarc        0
education         0
fpregnancy        0
gravity           0
height            0
hrt               0
hystrectomy       0
infertility       0
lactaton          0
marital           0
mens              0
no.biopsy         0
ocp               0
ocpuse            0
other.CA          0
personal.Hx       0
personal.other    0
reproduct         0
smoking           0
weight            0
dtype: int64


In [1228]:
df.to_csv('../data/processed/cleaned_data.csv', index=False)